# Generated by Django 4.0.5 on 2022-06-19 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='nome_receita',
            field=models.CharField(max_length=200, verbose_name='Nome da Receita'),
        ),
    ]
